apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: gb-ingress

spec:
  rules:
  - host: gb.local

    http:
      paths:
      - path: /
        pathType: Prefix

        backend:
          service:
            name: blue-service

            port:
              number: 80
