apiVersion: apps/v1
kind: Deployment

metadata:
  name: blue-deployment

spec:
  replicas: 3 

  selector:
    matchLabels:
      app: gb-app
      version: blue

  template:
    metadata:
      labels:
        app: gb-app
        version: blue

    spec:
      containers:
      - name: blue
        image: gb-app:v3

        imagePullPolicy: Never

        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"

          limits:
            memory: "128Mi"
            cpu: "250m"
        
        envFrom:
        - configMapRef:
            name: blue-config

        - secretRef:
            name: app-secret


        ports:
        - containerPort: 5000
